language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PACKAGE="mirage-vnetif"
  matrix:
  - DISTRO="debian-testing" OCAML_VERSION="4.09"
  - DISTRO="debian-unstable" OCAML_VERSION="4.08"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.07"
  - DISTRO="alpine" OCAML_VERSION="4.06"
