language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - ALCOTEST_SHOW_ERRORS=1
  - PINS="mirage-vnetif.dev:. mirage-vnetif-stack.dev:."
  matrix:
  - DISTRO="debian-stable" OCAML_VERSION="4.10" PACKAGE="mirage-vnetif-stack"
  - DISTRO="debian-testing" OCAML_VERSION="4.09" PACKAGE="mirage-vnetif"
  - DISTRO="debian-unstable" OCAML_VERSION="4.08" PACKAGE="mirage-vnetif"
  - DISTRO="ubuntu-16.04" OCAML_VERSION="4.07" PACKAGE="mirage-vnetif"
  - DISTRO="alpine" OCAML_VERSION="4.06" PACKAGE="mirage-vnetif"
